-- ─────────────────────────────────────────────────────────────────────────────
-- 007_model_usage.sql
-- Track every Anthropic API call: model, tokens, cost, task type.
-- Used to measure AI spend vs. value generated by the platform.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS nse.model_usage (
    id              BIGSERIAL PRIMARY KEY,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    worker          TEXT        NOT NULL,   -- e.g. 'ai_worker', 'event_detector'
    task            TEXT        NOT NULL,   -- e.g. 'signal_generation', 'event_classification'
    model           TEXT        NOT NULL,   -- e.g. 'claude-sonnet-4-6'
    ticker          TEXT,                   -- NULL for market-wide tasks
    input_tokens    INTEGER     NOT NULL DEFAULT 0,
    output_tokens   INTEGER     NOT NULL DEFAULT 0,
    cache_read_tokens INTEGER   NOT NULL DEFAULT 0,   -- prompt cache hits
    cache_write_tokens INTEGER  NOT NULL DEFAULT 0,   -- tokens written to cache
    -- Cost in USD (calculated at time of call using Anthropic list pricing)
    cost_usd        NUMERIC(10, 8) NOT NULL DEFAULT 0,
    -- Outcome: did we get a usable result?
    succeeded       BOOLEAN     NOT NULL DEFAULT TRUE,
    error_message   TEXT
);

CREATE INDEX IF NOT EXISTS model_usage_recorded_at_idx ON nse.model_usage (recorded_at DESC);
CREATE INDEX IF NOT EXISTS model_usage_model_idx        ON nse.model_usage (model);
CREATE INDEX IF NOT EXISTS model_usage_worker_idx       ON nse.model_usage (worker);

-- ── Daily cost summary view ───────────────────────────────────────────────────
CREATE OR REPLACE VIEW nse.daily_ai_cost AS
SELECT
    DATE(recorded_at AT TIME ZONE 'Africa/Nairobi') AS day,
    model,
    worker,
    COUNT(*)                       AS calls,
    SUM(input_tokens)              AS total_input_tokens,
    SUM(output_tokens)             AS total_output_tokens,
    SUM(cache_read_tokens)         AS total_cache_reads,
    SUM(cost_usd)                  AS total_cost_usd,
    COUNT(*) FILTER (WHERE NOT succeeded) AS failures
FROM nse.model_usage
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 5 DESC;

-- ── Grant read to anon for dashboard display ──────────────────────────────────
GRANT SELECT ON nse.model_usage TO anon, authenticated;
GRANT SELECT ON nse.daily_ai_cost TO anon, authenticated;
